const supplementaryDestinations = [
  {
    "name": "Gangtok",
    "country": "India",
    "state": "Sikkim",
    "city": "Gangtok",
    "category": "Hill Station",
    "description": "The capital of Sikkim, nestled in the eastern Himalayas, known for its Buddhist monasteries, clean streets, and majestic Kanchenjunga views.",
    "history": "Originally a small hamlet, Gangtok became a major pilgrimage site in the 1840s after the construction of the Enchey Monastery. It grew as a key transit point between Tibet and British India.",
    "culture": "Deeply influenced by Tibetan Buddhism. The city showcases vibrant Lepcha, Bhutia, and Nepali cultures, evident in its festivals, monasteries, and cuisine.",
    "language": "Nepali, Sikkimese, Hindi, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 27.3314, "lng": 88.6138 },
    "latitude": 27.3314,
    "longitude": 88.6138,
    "imageUrl": "https://images.unsplash.com/photo-1589136777351-fdc9c94aa5b9?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1589136777351-fdc9c94aa5b9?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Subtropical highland",
    "weather": "Cool, pleasant summers, mild monsoons, and cold winters with occasional snowfall nearby",
    "avgTemperature": "18°C",
    "bestTime": "October to May",
    "nearbyAirport": "Pakyong Airport (PYG)",
    "metroAvailable": false,
    "publicTransport": "Shared taxis, local cabs, ropeway",
    "budget": "Moderate",
    "estimatedBudgetMin": 2000,
    "estimatedBudgetMax": 7000,
    "hotels": ["Mayfair Spa Resort (Luxury)", "Elgin Nor-Khill (Luxury)", "Hotel Sonam Delek (Budget)"],
    "luxuryHotels": ["Mayfair Spa Resort", "Elgin Nor-Khill"],
    "budgetHotels": ["Hotel Sonam Delek", "Tag Resort"],
    "restaurants": ["The Square", "Nimtho (Sikkimese cuisine)", "Baker's Cafe"],
    "streetFood": ["Momo", "Thukpa", "Shaphaley"],
    "localFoods": ["Sikkimese Thali", "Phagshapa", "Gundruk"],
    "shoppingAreas": ["MG Marg", "Lal Bazaar", "Sikkim Handicrafts"],
    "nightlife": ["Cafe Live & Loud", "Casino Mahjong"],
    "attractions": ["Rumtek Monastery", "Tsomgo Lake", "Nathula Pass", "MG Marg"],
    "hiddenGems": ["Enchey Monastery", "Ganesh Tok Viewpoint"],
    "adventureActivities": ["Paragliding in Luing Resithang", "Trekking"],
    "familyActivities": ["Gangtok Ropeway ride", "Banjhakri Falls park"],
    "coupleActivities": ["Sunset walk at MG Marg", "Scenic cable car ride"],
    "soloTravelTips": "MG Marg is a clean litter-free zone. Ensure you have permits for Tsomgo Lake and Nathula Pass in advance.",
    "safetyScore": 10,
    "averageRating": 4.7,
    "totalReviews": 9,
    "nearbyPlaces": ["Tsomgo Lake", "Nathula Pass", "Rumtek"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Visit the majestic Rumtek Monastery, the seat of the Kagyu sect, and explore the prayer halls.",
        "afternoonPlan": "Head to Nimtho for authentic Sikkimese Thali. Walk around the clean, vehicle-free MG Marg in the afternoon.",
        "eveningPlan": "Take the Gangtok Ropeway for a bird's-eye view of the valley and have coffee at the Baker's Cafe.",
        "recommendedAttractions": ["Rumtek Monastery", "MG Marg"],
        "restaurants": ["Nimtho"],
        "localFood": ["Momo", "Thukpa"],
        "transportationTips": "Hire local shared cabs at designated stands to travel economically.",
        "estimatedDailyBudget": 2500
      }
    ]
  },
  {
    "name": "Kaziranga National Park",
    "country": "India",
    "state": "Assam",
    "city": "Kaziranga",
    "category": "Nature",
    "description": "A UNESCO World Heritage Site in Assam, sanctuary to two-thirds of the world's great one-horned rhinoceroses.",
    "history": "Established as a reserve forest in 1905 at the behest of Baroness Mary Curzon, it was declared a National Park in 1974 and a UNESCO site in 1985.",
    "culture": "The local communities celebrate Assamese Bihu. Traditional Assamese tea gardens surround the forest, showcasing colonial tea culture.",
    "language": "Assamese, Bengali, English, Hindi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 26.5775, "lng": 93.1711 },
    "latitude": 26.5775,
    "longitude": 93.1711,
    "imageUrl": "https://images.unsplash.com/photo-1612438214708-f428a707dd4e?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1612438214708-f428a707dd4e?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Subtropical monsoon",
    "weather": "Hot summers, heavy monsoon rains (flooding common in Jul-Aug), and pleasant dry winters",
    "avgTemperature": "24°C",
    "bestTime": "November to April",
    "nearbyAirport": "Jorhat Airport (JRH) - 97 km away",
    "metroAvailable": false,
    "publicTransport": "State transport buses, private taxis, jeep safaris",
    "budget": "Moderate",
    "estimatedBudgetMin": 3000,
    "estimatedBudgetMax": 9000,
    "hotels": ["Iora - The Retreat (Luxury)", "Borgos Resort (Moderate)", "Wild Grass Lodge (Budget)"],
    "luxuryHotels": ["Iora - The Retreat", "Borgos Resort"],
    "budgetHotels": ["Wild Grass Lodge", "Bon Habi Resort"],
    "restaurants": ["Hornbill Restaurant", "Maihang Restaurant"],
    "streetFood": ["Pitha", "Assamese tea snacks"],
    "localFoods": ["Masor Tenga (sour fish curry)", "Duck Meat curry", "Aloo Pitika"],
    "shoppingAreas": ["Kaziranga Local Craft Market", "Kohora Bazaar"],
    "nightlife": ["Quiet resort campfires"],
    "attractions": ["Kaziranga Elephant Safari", "Bagori Range Jeep Safari", "Orchid Park"],
    "hiddenGems": ["Kakochang Waterfalls", "Hathikuli Tea Estate"],
    "adventureActivities": ["Jeep Safari", "Elephant Safari", "Bird Watching"],
    "familyActivities": ["Visiting the Kaziranga National Orchid and Biodiversity Park"],
    "coupleActivities": ["Sunset watch over Brahmaputra riverbanks", "Tea garden walk"],
    "soloTravelTips": "Book safaris well in advance online or at the ticket counter in Kohora.",
    "safetyScore": 9,
    "averageRating": 4.6,
    "totalReviews": 5,
    "nearbyPlaces": ["Jorhat", "Tezpur", "Guwahati"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Take the early morning Elephant Safari in the Central Range (Kohora) to spot Rhinos in the grass fog.",
        "afternoonPlan": "Eat lunch at Maihang. Visit the Kaziranga Orchid Park to see over 500 species of orchids and traditional Assamese dances.",
        "eveningPlan": "Go on a late afternoon Jeep Safari in the Western Range (Bagori) to observe herds of wild buffalo and elephants.",
        "recommendedAttractions": ["Elephant Safari", "Orchid Park"],
        "restaurants": ["Maihang Restaurant"],
        "localFood": ["Masor Tenga"],
        "transportationTips": "Jeeps are required inside the park; organize them through licensed guides/resorts.",
        "estimatedDailyBudget": 3500
      }
    ]
  },
  {
    "name": "Shillong",
    "country": "India",
    "state": "Meghalaya",
    "city": "Shillong",
    "category": "Hill Station",
    "description": "Known as the 'Scotland of the East', Shillong offers cascading waterfalls, green pine forests, and cool mountain weather.",
    "history": "Shillong was a small village until it became the civil station of the Khasi and Jaintia Hills in 1864 under British rule. It served as the capital of composite Assam before Meghalaya was created.",
    "culture": "Predominantly inhabited by the Khasi tribe. Matrilineal social structure, famous local indie rock bands, and football enthusiasm define its modern culture.",
    "language": "Khasi, English, Assamese, Hindi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 25.5788, "lng": 91.8933 },
    "latitude": 25.5788,
    "longitude": 91.8933,
    "imageUrl": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Subtropical highland",
    "weather": "Warm, wet summers (heavy rains nearby), and cool, dry winters",
    "avgTemperature": "17°C",
    "bestTime": "September to May",
    "nearbyAirport": "Shillong Airport (SHL) in Umroi - 30 km away",
    "metroAvailable": false,
    "publicTransport": "Local black-and-yellow shared cabs, tourist taxis",
    "budget": "Moderate",
    "estimatedBudgetMin": 1800,
    "estimatedBudgetMax": 6500,
    "hotels": ["Heritage Club - Tripura Castle (Luxury)", "Hotel Center Point (Moderate)", "Polo Towers (Moderate)"],
    "luxuryHotels": ["Heritage Club - Tripura Castle", "Ri Kynjai Resort"],
    "budgetHotels": ["White House Guest House", "Youth Hostel Shillong"],
    "restaurants": ["Cafe Shillong", "Dylan's Cafe", "Trattoria (Local Khasi food)"],
    "streetFood": ["Jadoh", "Dohneiiong", "Momos"],
    "localFoods": ["Jadoh (rice with meat)", "Dohkhlieh (pork salad)", "Tungrymbai"],
    "shoppingAreas": ["Police Bazar", "Bara Bazar (Lewduh Market)"],
    "nightlife": ["Cloud 9 lounge", "The Evening Club"],
    "attractions": ["Shillong Peak", "Elephant Falls", "Umiam Lake", "Don Bosco Museum"],
    "hiddenGems": ["Laitlum Canyons", "Ward's Lake"],
    "adventureActivities": ["Boating at Umiam Lake", "Trekking the David Scott Trail"],
    "familyActivities": ["Boating in Ward's Lake", "Picnic at Elephant Falls"],
    "coupleActivities": ["Sunset views from Laitlum Canyons", "Stroll around Umiam Lake"],
    "soloTravelTips": "Shared cabs are very cheap; just declare your destination when stopping them on the road.",
    "safetyScore": 10,
    "averageRating": 4.6,
    "totalReviews": 7,
    "nearbyPlaces": ["Cherrapunji", "Dawki", "Mawlynnong"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Drive up to Shillong Peak for a panorama, then check out the three-tiered Elephant Falls.",
        "afternoonPlan": "Lunch at Trattoria to sample traditional Khasi Jadoh. Spend the afternoon exploring the 7-floor Don Bosco Museum.",
        "eveningPlan": "Walk around Ward's Lake and enjoy a cup of local tea at Cafe Shillong while listening to local rock music.",
        "recommendedAttractions": ["Elephant Falls", "Don Bosco Museum"],
        "restaurants": ["Trattoria", "Cafe Shillong"],
        "localFood": ["Jadoh"],
        "transportationTips": "Shared cabs are convenient for getting around the city core.",
        "estimatedDailyBudget": 2200
      }
    ]
  },
  {
    "name": "Bodh Gaya",
    "country": "India",
    "state": "Bihar",
    "city": "Bodh Gaya",
    "category": "Heritage",
    "description": "The place where Prince Siddhartha attained enlightenment under the Bodhi Tree and became the Buddha.",
    "history": "In 500 BC, Siddhartha Gautama attained enlightenment here. King Ashoka built the first temple on the site in the 3rd century BC. The current Mahabodhi Temple complex is a UNESCO World Heritage Site.",
    "culture": "A global Buddhist pilgrimage destination. Temples built by Bhutan, Thailand, Japan, and Myanmar showcase diverse international architectural styles.",
    "language": "Hindi, Magahi, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 24.6961, "lng": 84.9870 },
    "latitude": 24.6961,
    "longitude": 84.9870,
    "imageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Subtropical dry",
    "weather": "Very hot summers (April-June), monsoon rains (July-September), and cool, dry winters",
    "avgTemperature": "26°C",
    "bestTime": "October to March",
    "nearbyAirport": "Gaya Airport (GAY) - 10 km away",
    "metroAvailable": false,
    "publicTransport": "Auto-rickshaws, cycle-rickshaws, e-rickshaws",
    "budget": "Budget",
    "estimatedBudgetMin": 1000,
    "estimatedBudgetMax": 4500,
    "hotels": ["The Bodhgaya Hotel (Moderate)", "Maha Bodhi Hotel (Luxury)", "Kirti Guest House (Budget)"],
    "luxuryHotels": ["Maha Bodhi Hotel Resort", "Royal Residency"],
    "budgetHotels": ["Kirti Guest House", "Tara Guest House"],
    "restaurants": ["Sujata Restaurant", "Be Happy Cafe", "Fujiya Green"],
    "streetFood": ["Litti Chokha", "Anarsa", "Samosa Chaat"],
    "localFoods": ["Litti Chokha", "Sattu Paratha", "Tilkut"],
    "shoppingAreas": ["Mahabodhi Temple Market", "Tibetan Refugee Market"],
    "nightlife": ["Meditation, chanting halls"],
    "attractions": ["Mahabodhi Temple", "Great Buddha Statue", "Bodhi Tree", "Muchalinda Lake"],
    "hiddenGems": ["Dungeshwari Cave Temples", "Sujata Kuti"],
    "adventureActivities": ["Bicycle tours", "Heritage walks"],
    "familyActivities": ["Walking around Mahabodhi garden", "Viewing international monasteries"],
    "coupleActivities": ["Meditation in the peace park", "Visiting local stupas"],
    "soloTravelTips": "Observe temple rules: remove shoes, maintain absolute silence in the inner sanctuary. Phones are not allowed inside.",
    "safetyScore": 8,
    "averageRating": 4.5,
    "totalReviews": 3,
    "nearbyPlaces": ["Gaya", "Nalanda", "Rajgir"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Visit the UNESCO Mahabodhi Temple and sit quietly under the sacred Bodhi Tree where Buddha meditated.",
        "afternoonPlan": "Have lunch at Be Happy Cafe. Visit the giant 80-foot Great Buddha Statue.",
        "eveningPlan": "Explore the peaceful Thai, Japanese, and Tibetan monasteries to see diverse Buddhist traditions.",
        "recommendedAttractions": ["Mahabodhi Temple", "Great Buddha Statue"],
        "restaurants": ["Be Happy Cafe"],
        "localFood": ["Litti Chokha"],
        "transportationTips": "Eco-friendly e-rickshaws are the best way to move around the town.",
        "estimatedDailyBudget": 1200
      }
    ]
  },
  {
    "name": "Gir National Park",
    "country": "India",
    "state": "Gujarat",
    "city": "Sasan Gir",
    "category": "Nature",
    "description": "The sole remaining natural habitat of the majestic Asiatic Lion, located in Saurashtra, Gujarat.",
    "history": "By the early 20th century, hunting reduced the lion population to less than 20. The Nawab of Junagadh protected the forest, paving the way for it to become a national park in 1965.",
    "culture": "Home to the Maldhari pastoralists and the Siddi tribe (Afro-Indians) who have coexisted with the lions for centuries.",
    "language": "Gujarati, Hindi, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 21.1244, "lng": 70.8241 },
    "latitude": 21.1244,
    "longitude": 70.8241,
    "imageUrl": "https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Semi-arid",
    "weather": "Scorching dry summers, brief heavy monsoon (closed Jun-Oct), and pleasant dry winters",
    "avgTemperature": "27°C",
    "bestTime": "December to April",
    "nearbyAirport": "Keshod Airport (IXK) - 60 km / Rajkot Airport (RAJ) - 160 km",
    "metroAvailable": false,
    "publicTransport": "GSRTC buses, private safari gypsies",
    "budget": "Moderate",
    "estimatedBudgetMin": 2500,
    "estimatedBudgetMax": 8500,
    "hotels": ["The Fern Gir Forest Resort (Luxury)", "Gir Birding Lodge (Moderate)", "Sasan Gir Guest House (Budget)"],
    "luxuryHotels": ["The Fern Gir Forest Resort", "Woods at Sasan"],
    "budgetHotels": ["Gir Birding Lodge", "Lion Safari Camp"],
    "restaurants": ["Gir Kathiyawadi Dhaba", "Sankalp Restaurant"],
    "streetFood": ["Khaman Dhokla", "Fafda Jalebi"],
    "localFoods": ["Kathiyawadi Thali", "Sev Tameta curry", "Rotla with ghee"],
    "shoppingAreas": ["Sasan Gir Local Handicraft Stall"],
    "nightlife": ["Quiet campfire resorts"],
    "attractions": ["Gir Jungle Trail", "Devalia Safari Park", "Kamleshwar Dam"],
    "hiddenGems": ["Kankai Mata Temple inside park"],
    "adventureActivities": ["Lion Safari Jeep Tour", "Bird Watching"],
    "familyActivities": ["Devalia Park bus tour", "Nature interpretation center"],
    "coupleActivities": ["Romantic jungle dinners in luxury camps"],
    "soloTravelTips": "Book permits for the Gir Jungle Trail months in advance on the official government portal. The park is closed from June 16 to October 15.",
    "safetyScore": 9,
    "averageRating": 4.5,
    "totalReviews": 4,
    "nearbyPlaces": ["Somnath", "Junagadh", "Diu"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Take the early morning (6:00 AM) open jeep safari on the Gir Jungle Trail to catch sights of Asiatic lions.",
        "afternoonPlan": "Enjoy a spicy Kathiyawadi Thali at Gir Kathiyawadi Dhaba. Visit the Devalia Safari Park (bus safari zone).",
        "eveningPlan": "Relax at the resort, listen to tribal Siddi Dhamal dance performances arranged by the hotels.",
        "recommendedAttractions": ["Gir Jungle Trail", "Devalia Safari Park"],
        "restaurants": ["Gir Kathiyawadi Dhaba"],
        "localFood": ["Kathiyawadi Thali"],
        "transportationTips": "Official safari gypsies must be booked online via the Gujarat Tourism portal.",
        "estimatedDailyBudget": 3000
      }
    ]
  },
  {
    "name": "Puri",
    "country": "India",
    "state": "Odisha",
    "city": "Puri",
    "category": "Beach",
    "description": "A historic sacred beach city in Odisha, famous for the Jagannath Temple and the annual Rath Yatra chariot festival.",
    "history": "Dating back to the 3rd century BC, Puri is one of the Char Dham pilgrimage sites. The famous Jagannath Temple was constructed by King Anantavarman Chodaganga Deva in the 12th century AD.",
    "culture": "Intricately linked to the Jagannath cult. The city is famous for Odissi dance, sand art by Sudarsan Pattnaik, and handloom Applique crafts.",
    "language": "Odia, Bengali, Hindi, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 19.8135, "lng": 85.8312 },
    "latitude": 19.8135,
    "longitude": 85.8312,
    "imageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Tropical wet and dry",
    "weather": "Hot, humid summers, heavy monsoons, and mild, windy winters",
    "avgTemperature": "27°C",
    "bestTime": "October to March",
    "nearbyAirport": "Biju Patnaik Airport (BBI) in Bhubaneswar - 60 km away",
    "metroAvailable": false,
    "publicTransport": "Local buses, auto-rickshaws, cycle-rickshaws",
    "budget": "Moderate",
    "estimatedBudgetMin": 1500,
    "estimatedBudgetMax": 5000,
    "hotels": ["Mayfair Waves (Luxury)", "Hans Coco Palms (Moderate)", "Z Hotel Puri (Budget)"],
    "luxuryHotels": ["Mayfair Waves", "Toshali Sands"],
    "budgetHotels": ["Z Hotel Puri", "Hotel Sea Green"],
    "restaurants": ["Wildgrass Restaurant", "Chung Wah Restaurant"],
    "streetFood": ["Chhena Poda", "Gupchup", "Rasagola"],
    "localFoods": ["Mahaprasad (cooked in clay pots)", "Dalma", "Pakhala Bhata"],
    "shoppingAreas": ["Swargadwar Beach Market", "Pipli Applique Village nearby"],
    "nightlife": ["Beachside stalls, starlight walks"],
    "attractions": ["Jagannath Temple", "Puri Beach", "Golden Beach (Blue Flag)", "Chilika Lake day trip"],
    "hiddenGems": ["Raghurajpur Heritage Crafts Village", "Balighai Beach"],
    "adventureActivities": ["Surfing at Ramachandi Beach", "Boating in Chilika"],
    "familyActivities": ["Relaxing on Golden Beach", "Shopping at Swargadwar bazaar"],
    "coupleActivities": ["Watching the sunrise at Puri beach", "Visiting Sun Temple Konark (35 km)"],
    "soloTravelTips": "Non-Hindus are not allowed inside the inner sanctum of Jagannath Temple, but can get a view of the temple complex from the library rooftop opposite.",
    "safetyScore": 9,
    "averageRating": 4.4,
    "totalReviews": 4,
    "nearbyPlaces": ["Konark", "Bhubaneswar", "Chilika Lake"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Visit the famous Jagannath Temple to admire its Kalinga architecture and witness the temple flag changing ceremony.",
        "afternoonPlan": "Savor the sacred Mahaprasad lunch. Visit Raghurajpur heritage crafts village to see Pattachitra painters.",
        "eveningPlan": "Relax at Golden Beach (Blue Flag certified) and enjoy local Odia sweet Chhena Poda at Swargadwar.",
        "recommendedAttractions": ["Jagannath Temple", "Golden Beach"],
        "restaurants": ["Wildgrass Restaurant"],
        "localFood": ["Chhena Poda"],
        "transportationTips": "Eco-friendly cycle rickshaws are cheap and perfect for local lanes.",
        "estimatedDailyBudget": 1800
      }
    ]
  },
  {
    "name": "Chitrakote Falls",
    "country": "India",
    "state": "Chhattisgarh",
    "city": "Jagdalpur",
    "category": "Nature",
    "description": "The widest waterfall in India, often called the 'Niagara Falls of India', located in the Bastar region.",
    "history": "Formed by the Indravati River, the falls have been a sacred tribal site for the indigenous Bastar tribes for centuries.",
    "culture": "Deeply tied to the Bastar tribal culture. The Bastar Dussehra is the longest festival in the world (75 days) and showcases colorful local traditions.",
    "language": "Halbi, Gondi, Hindi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 19.2008, "lng": 81.7766 },
    "latitude": 19.2008,
    "longitude": 81.7766,
    "imageUrl": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Tropical wet and dry",
    "weather": "Humid summers, massive monsoon waters (falls at their peak in Jul-Sep), and dry winters",
    "avgTemperature": "25°C",
    "bestTime": "July to February",
    "nearbyAirport": "Jagdalpur Airport (JGB) - 38 km / Raipur Airport (RPR) - 290 km",
    "metroAvailable": false,
    "publicTransport": "Local buses to Jagdalpur, private rental cabs",
    "budget": "Budget",
    "estimatedBudgetMin": 1200,
    "estimatedBudgetMax": 5000,
    "hotels": ["Dandami Luxury Resort (Moderate)", "Bastar Jungle Resort (Moderate)", "Hotel Rainbow Jagdalpur (Budget)"],
    "luxuryHotels": ["Dandami Luxury Resort"],
    "budgetHotels": ["Hotel Rainbow", "Royal Bastar Farm"],
    "restaurants": ["Resort restaurant", "Bastar Food court"],
    "streetFood": ["Bastar tribal snacks"],
    "localFoods": ["Chana Koli", "Bastar tribal Thali", "Mahua drink (local)"],
    "shoppingAreas": ["Jagdalpur tribal handicraft market (Bell metal, Terracotta)"],
    "nightlife": ["Quiet star gazing"],
    "attractions": ["Chitrakote Waterfall", "Kanger Valley National Park", "Kutumsar Caves", "Teerathgarh Falls"],
    "hiddenGems": ["Tamra Ghoomar Falls", "Mendri Ghoomar Valley"],
    "adventureActivities": ["Coracle boat ride at the foot of falls", "Spelunking in Kutumsar caves"],
    "familyActivities": ["Picnic in the gardens overlooking falls"],
    "coupleActivities": ["Watching illuminated waterfalls at night"],
    "soloTravelTips": "Take a coracle boat ride (traditional round boat) right near the spray of the waterfall for an amazing close-up view.",
    "safetyScore": 8,
    "averageRating": 4.4,
    "totalReviews": 3,
    "nearbyPlaces": ["Jagdalpur", "Raipur", "Teerathgarh"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Marvel at the giant horseshoe-shaped Chitrakote Falls and take the stairs down for a coracle boat ride near the spray.",
        "afternoonPlan": "Lunch at Dandami Resort. Visit the nearby Kanger Valley National Park and explore Kutumsar limestone caves.",
        "eveningPlan": "Return to the falls to witness them beautifully illuminated with multi-colored floodlights at sunset.",
        "recommendedAttractions": ["Chitrakote Waterfall", "Kutumsar Caves"],
        "restaurants": ["Dandami Resort Restaurant"],
        "localFood": ["Bastar tribal Thali"],
        "transportationTips": "Hire a private cab from Jagdalpur for comfortable regional transport.",
        "estimatedDailyBudget": 2000
      }
    ]
  },
  {
    "name": "Gurugram",
    "country": "India",
    "state": "Haryana",
    "city": "Gurugram",
    "category": "Metro",
    "description": "India's Millennium City — a bustling financial and technological hub featuring futuristic glass skyscrapers and premium entertainment parks.",
    "history": "Traditionally identified as the village of Guru Dronacharya from the Mahabharata. It was a sleepy agricultural town until the late 1970s when Maruti Suzuki established a factory, sparking an urban boom.",
    "culture": "A modern urban corporate hub with a highly diverse expatriate and cosmopolitan community.",
    "language": "Hindi, English, Haryanvi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 28.4595, "lng": 77.0266 },
    "latitude": 28.4595,
    "longitude": 77.0266,
    "imageUrl": "https://images.unsplash.com/photo-1595928642581-f50f4f3453a5?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1595928642581-f50f4f3453a5?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Semi-arid",
    "weather": "Hot summers, monsoon rain, and chilly foggy winters",
    "avgTemperature": "25°C",
    "bestTime": "October to March",
    "nearbyAirport": "Indira Gandhi International Airport (DEL) - 15 km away",
    "metroAvailable": true,
    "publicTransport": "Delhi Metro, Gurugram Rapid Metro, auto-rickshaws, Uber/Ola",
    "budget": "Luxury",
    "estimatedBudgetMin": 3000,
    "estimatedBudgetMax": 15000,
    "hotels": ["The Oberoi Gurgaon (Luxury)", "Leela Ambience (Luxury)", "Ibis Gurgaon (Budget)"],
    "luxuryHotels": ["The Oberoi Gurgaon", "Westin Sohna Resort"],
    "budgetHotels": ["Ibis Gurgaon", "Ginger Manesar"],
    "restaurants": ["Farzi Cafe", "Cyber Hub Social", "Spectra"],
    "streetFood": ["Samosas", "Golgappa at Sector 14", "Chhole Bhature"],
    "localFoods": ["Kadhi Chawal", "Haryanvi Bajra Khichdi", "Tandoori Chicken"],
    "shoppingAreas": ["Ambience Mall", "Galleria Market", "Sector 29"],
    "nightlife": ["Cyber Hub microbreweries", "Sector 29 clubs"],
    "attractions": ["Cyber Hub", "Kingdom of Dreams", "Sultanpur National Park", "Damdama Lake"],
    "hiddenGems": ["Museum of Folk and Tribal Art", "Tau Devi Lal Bio Diversity Park"],
    "adventureActivities": ["Go-karting at Kartomania", "Hot air ballooning in Damdama"],
    "familyActivities": ["Boating at Damdama Lake", "Bird watching at Sultanpur sanctuary"],
    "coupleActivities": ["Brewery tour at Cyber Hub", "Resort spa weekend in Sohna"],
    "soloTravelTips": "Use the Rapid Metro for quick office-district transit. Cyber Hub is safe and open late for dining.",
    "safetyScore": 7,
    "averageRating": 4.1,
    "totalReviews": 4,
    "nearbyPlaces": ["Delhi", "Noida", "Faridabad"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Go bird watching at Sultanpur National Park, home to migratory birds in winter.",
        "afternoonPlan": "Lunch at Cyber Hub Social. Spend the afternoon shopping at Ambience Mall, one of India's largest malls.",
        "eveningPlan": "Enjoy craft beer and live music at a local microbrewery in Sector 29.",
        "recommendedAttractions": ["Sultanpur National Park", "Cyber Hub"],
        "restaurants": ["Cyber Hub Social"],
        "localFood": ["Kadhi Chawal"],
        "transportationTips": "Rapid Metro is ideal for skipping traffic in the Cyber City loop.",
        "estimatedDailyBudget": 4000
      }
    ]
  },
  {
    "name": "Ranchi",
    "country": "India",
    "state": "Jharkhand",
    "city": "Ranchi",
    "category": "Nature",
    "description": "The City of Waterfalls, Ranchi is surrounded by green hills, waterfalls, and mineral-rich forests.",
    "history": "Historically part of the Chhota Nagpur plateau, Ranchi served as the summer capital of Bihar during British rule due to its cool climate.",
    "culture": "Rich tribal heritage (Santhal, Munda, and Oraon tribes). Famous for tribal wood carvings, metalwork, and Sarhul festival.",
    "language": "Hindi, Nagpuri, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 23.3441, "lng": 85.3096 },
    "latitude": 23.3441,
    "longitude": 85.3096,
    "imageUrl": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Humid subtropical",
    "weather": "Mild summers, monsoon rains, and pleasant dry winters",
    "avgTemperature": "23°C",
    "bestTime": "September to April",
    "nearbyAirport": "Birsa Munda Airport (IXR)",
    "metroAvailable": false,
    "publicTransport": "Auto-rickshaws, cycle-rickshaws, local city buses",
    "budget": "Moderate",
    "estimatedBudgetMin": 1500,
    "estimatedBudgetMax": 5000,
    "hotels": ["Radisson Blu Ranchi (Luxury)", "Chanakya BNR (Moderate)", "Hotel Green Horizon (Budget)"],
    "luxuryHotels": ["Radisson Blu Ranchi", "Chanakya BNR Hotel"],
    "budgetHotels": ["Hotel Green Horizon", "Hotel Capitol Hill"],
    "restaurants": ["Kaveri Restaurant", "The Yellow Chilli"],
    "streetFood": ["Dhuska with Chana-Aloo", "Litti Chokha", "Chowmein"],
    "localFoods": ["Dhuska", "Madua Roti", "Chilka Roti"],
    "shoppingAreas": ["Firayalal Chowk", "PVR Plaza Mall"],
    "nightlife": ["Radisson lounge, Sector clubs"],
    "attractions": ["Hundru Falls", "Jonha Falls", "Dassam Falls", "Ranchi Lake"],
    "hiddenGems": ["Patratu Valley", "Tagore Hill"],
    "adventureActivities": ["Rock climbing at Tagore Hill", "Boating at Patratu Dam"],
    "familyActivities": ["Cable car at Rock Garden", "Ranchi zoo visit"],
    "coupleActivities": ["Sunset drive through Patratu Valley hairpin bends"],
    "soloTravelTips": "Dhuska is the ultimate local breakfast. Try it at local dhabas near Firayalal.",
    "safetyScore": 8,
    "averageRating": 4.2,
    "totalReviews": 3,
    "nearbyPlaces": ["Jamshedpur", "Netarhat", "Deoghar"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Visit Hundru Falls where the Subarnarekha River falls from 320 feet. Walk down the stairs to the pool.",
        "afternoonPlan": "Lunch at Kaveri Restaurant. Visit Tagore Hill, the former ashram of Rabindranath Tagore's family.",
        "eveningPlan": "Take a scenic drive through the spectacular winding roads of Patratu Valley and watch the sunset over the dam.",
        "recommendedAttractions": ["Hundru Falls", "Patratu Valley"],
        "restaurants": ["Kaveri Restaurant"],
        "localFood": ["Dhuska"],
        "transportationTips": "Rent a car for the day; waterfalls are located 30-40 km outside the city.",
        "estimatedDailyBudget": 2200
      }
    ]
  },
  {
    "name": "Imphal",
    "country": "India",
    "state": "Manipur",
    "city": "Imphal",
    "category": "Heritage",
    "description": "The capital of Manipur, surrounded by hills and home to the unique Kangla Fort and the world's only floating national park.",
    "history": "Seat of the ancient Meitei Kingdom of Manipur. It was the site of the Battle of Imphal in 1944, a major turning point in World War II where Allied forces defeated the Japanese army.",
    "culture": "Famous for the classical Manipuri Jagoi dance, polo (Manipur is the birthplace of modern polo), and the Ima Keithel (Mother's Market) run entirely by women.",
    "language": "Manipuri (Meitei), English, Hindi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 24.8170, "lng": 93.9368 },
    "latitude": 24.8170,
    "longitude": 93.9368,
    "imageUrl": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Humid subtropical",
    "weather": "Warm summers, heavy monsoons, and mild pleasant winters",
    "avgTemperature": "21°C",
    "bestTime": "October to April",
    "nearbyAirport": "Bir Tikendrajit International Airport (IMF)",
    "metroAvailable": false,
    "publicTransport": "Shared auto-rickshaws, local buses, cycle-rickshaws",
    "budget": "Moderate",
    "estimatedBudgetMin": 1800,
    "estimatedBudgetMax": 6000,
    "hotels": ["Classic Grande (Luxury)", "The Classic Hotel (Moderate)", "Hotel Imphal (Moderate)"],
    "luxuryHotels": ["Classic Grande"],
    "budgetHotels": ["Hotel Imphal", "Youth Hostel Imphal"],
    "restaurants": ["Luxmi Kitchen (traditional Meitei cuisine)", "Flavours Restaurant"],
    "streetFood": ["Singju (spicy cabbage salad)", "Kanghou"],
    "localFoods": ["Eromba (mashed vegetables and fish)", "Meitei Thali", "Chak-hao Kheer (black rice pudding)"],
    "shoppingAreas": ["Ima Keithel (Mother's Market)", "Paona Bazaar"],
    "nightlife": ["Very quiet, traditional home stays"],
    "attractions": ["Kangla Fort", "Loktak Lake (floating islands)", "Keibul Lamjao National Park", "Ima Keithel"],
    "hiddenGems": ["Red Hill Lokpaching (WWII Peace memorial)", "Singda Dam"],
    "adventureActivities": ["Boating in Loktak Lake", "Hiking in Shirui hills nearby"],
    "familyActivities": ["Exploring Kangla Fort museum", "Walking in Kakching Garden"],
    "coupleActivities": ["Boat ride to Sendra Island on Loktak Lake"],
    "soloTravelTips": "Ima Keithel is run by over 5000 married women. It is a fantastic place to buy local handlooms and organic bamboo shoots.",
    "safetyScore": 8,
    "averageRating": 4.3,
    "totalReviews": 3,
    "nearbyPlaces": ["Loktak Lake", "Moreh", "Kohima"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Explore the historic Kangla Fort, the ancient royal seat, and visit the sacred temples inside.",
        "afternoonPlan": "Lunch at Luxmi Kitchen to try traditional Meitei Eromba. Shop at the famous all-women Ima Keithel market.",
        "eveningPlan": "Drive to Loktak Lake to watch the sunset over the floating Phumdis (vegetation islands).",
        "recommendedAttractions": ["Kangla Fort", "Ima Keithel"],
        "restaurants": ["Luxmi Kitchen"],
        "localFood": ["Chak-hao Kheer"],
        "transportationTips": "Rent a private taxi to comfortably visit Loktak Lake (48 km away).",
        "estimatedDailyBudget": 2200
      }
    ]
  },
  {
    "name": "Aizawl",
    "country": "India",
    "state": "Mizoram",
    "city": "Aizawl",
    "category": "Hill Station",
    "description": "The capital of Mizoram, set on a steep ridge with picturesque white houses overlooking green valleys and cloud forests.",
    "history": "Aizawl was established as a military outpost by the British in 1890 during campaigns in the Lushai Hills. It grew post-independence as the administrative hub of Mizoram.",
    "culture": "Rich Mizo tribal culture. Extremely clean, orderly traffic (famous for no-honking rule), and vibrant church choir music define the town.",
    "language": "Mizo, English, Hindi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 23.7271, "lng": 92.7176 },
    "latitude": 23.7271,
    "longitude": 92.7176,
    "imageUrl": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Subtropical highland",
    "weather": "Mild, breezy summers, heavy monsoon rains, and cool dry winters",
    "avgTemperature": "20°C",
    "bestTime": "October to April",
    "nearbyAirport": "Lengpui Airport (AJL) - 30 km away",
    "metroAvailable": false,
    "publicTransport": "Local taxis, city buses, shared auto-rickshaws",
    "budget": "Moderate",
    "estimatedBudgetMin": 1500,
    "estimatedBudgetMax": 5500,
    "hotels": ["Hotel Ritz (Moderate)", "Hotel Regency (Moderate)", "Tourist Lodge Chaltlang (Budget)"],
    "luxuryHotels": ["Hotel Ritz"],
    "budgetHotels": ["Tourist Lodge Chaltlang", "Hotel Chief"],
    "restaurants": ["Red Pepper (Mizo tribal food)", "Zote Bakery"],
    "streetFood": ["Mizo snacks", "Steamed momos"],
    "localFoods": ["Bai (stew with pork and bamboo shoot)", "Vawksa Rep (smoked pork)", "Sawhchiar"],
    "shoppingAreas": ["Bara Bazar", "Millennium Centre"],
    "nightlife": ["Gospel choir concerts, quiet evenings"],
    "attractions": ["Solomon's Temple", "Mizoram State Museum", "Durtlang Hills view point", "Reiek Tlang"],
    "hiddenGems": ["Khuangchera Puk (cave)", "Sasa Resort"],
    "adventureActivities": ["Trekking to Reiek Peak", "Exploring caves"],
    "familyActivities": ["Visiting the State Museum", "Picnic at Hmuifang hills"],
    "coupleActivities": ["Watching the night lights of Aizawl from Durtlang viewpoint"],
    "soloTravelTips": "Observe the local strict traffic rules. Pedestrians have absolute right of way, and drivers never honk.",
    "safetyScore": 10,
    "averageRating": 4.4,
    "totalReviews": 3,
    "nearbyPlaces": ["Reiek", "Lunglei", "Champhai"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Explore the beautiful white marble Solomon's Temple, and visit the Mizoram State Museum to see Mizo tribal relics.",
        "afternoonPlan": "Lunch at Red Pepper for smoked pork Bai. Drive up to Durtlang Hills for a stunning view of Aizawl.",
        "eveningPlan": "Stroll through Bara Bazar to buy local hand-woven Mizo Puan skirts, and dine at the Ritz.",
        "recommendedAttractions": ["Solomon's Temple", "Durtlang Hills"],
        "restaurants": ["Red Pepper"],
        "localFood": ["Vawksa Rep"],
        "transportationTips": "Taxis are standard; city buses run on fixed routes along the ridges.",
        "estimatedDailyBudget": 2000
      }
    ]
  },
  {
    "name": "Kohima",
    "country": "India",
    "state": "Nagaland",
    "city": "Kohima",
    "category": "Hill Station",
    "description": "The capital of Nagaland, famous for the WWII War Cemetery, scenic hills, and the Hornbill Festival in December.",
    "history": "Originally a village of the Angami Naga tribe. It was the site of the Battle of Kohima in 1944, often described as the 'Stalingrad of the East', where British and Indian troops stopped the Japanese invasion.",
    "culture": "Celebrates the grand Hornbill Festival at Kisama Heritage Village every December, showcasing dances, music, and food of Nagaland's 17 major tribes.",
    "language": "Nagamese, English, Hindi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 25.6751, "lng": 94.1086 },
    "latitude": 25.6751,
    "longitude": 94.1086,
    "imageUrl": "https://images.unsplash.com/photo-1589136777351-fdc9c94aa5b9?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1589136777351-fdc9c94aa5b9?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Subtropical highland",
    "weather": "Pleasant summers, wet monsoons, and chilly, dry winters",
    "avgTemperature": "19°C",
    "bestTime": "October to May",
    "nearbyAirport": "Dimapur Airport (DMU) - 74 km away",
    "metroAvailable": false,
    "publicTransport": "Local shared taxis, rental cabs",
    "budget": "Moderate",
    "estimatedBudgetMin": 2000,
    "estimatedBudgetMax": 7000,
    "hotels": ["Hotel Japfu (Moderate)", "Hotel Vivor (Luxury)", "Classic hotel Kohima (Moderate)"],
    "luxuryHotels": ["Hotel Vivor"],
    "budgetHotels": ["Hotel Japfu", "Razhu Pru Guest House"],
    "restaurants": ["Savour Restaurant", "Dream Cafe"],
    "streetFood": ["Naga smoked meats", "Bamboo shoot soup"],
    "localFoods": ["Smoked Pork with Axone", "Galho (Naga khichdi)", "Zutho (local rice beer)"],
    "shoppingAreas": ["Kohima Local Market", "Kisama souvenir shops"],
    "nightlife": ["Indie rock gigs, quiet hills"],
    "attractions": ["Kohima War Cemetery", "Kisama Heritage Village", "Dzukou Valley", "Kohima Cathedral"],
    "hiddenGems": ["Khonoma Green Village", "Japfu Peak"],
    "adventureActivities": ["Trekking in Dzukou Valley", "Hiking Japfu Peak"],
    "familyActivities": ["Exploring the WWII museum at Kisama", "Walking in municipal parks"],
    "coupleActivities": ["Dzukou Valley camping", "Scenic drives to Khonoma"],
    "soloTravelTips": "Khonoma (20 km away) is India's first green village, renowned for conservation, clean lanes, and stone monuments.",
    "safetyScore": 9,
    "averageRating": 4.5,
    "totalReviews": 4,
    "nearbyPlaces": ["Dimapur", "Khonoma", "Imphal"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Visit the poignant Kohima War Cemetery, dedicated to Allied soldiers of WWII. Hike up the cemetery terraces.",
        "afternoonPlan": "Lunch at Savour. Drive to Kisama Heritage Village to see traditional Naga houses (Morungs).",
        "eveningPlan": "Enjoy sunset from the deck of Dream Cafe, sipping Naga coffee overlooking the steep hills.",
        "recommendedAttractions": ["Kohima War Cemetery", "Kisama Heritage Village"],
        "restaurants": ["Savour Restaurant"],
        "localFood": ["Galho"],
        "transportationTips": "Hire a private cab for the day to visit Kisama and Khonoma village.",
        "estimatedDailyBudget": 2500
      }
    ]
  },
  {
    "name": "Tawang",
    "country": "India",
    "state": "Arunachal Pradesh",
    "city": "Tawang",
    "category": "Hill Station",
    "description": "Located at 10,000 feet in Arunachal Pradesh, Tawang is famous for its massive Buddhist monastery, pristine lakes, and snow-capped mountain passes.",
    "history": "Historically part of Tibet. The Tawang Monastery was founded in 1681 by Merak Lama Lodre Gyatso according to the wishes of the 5th Dalai Lama. It was the birthplace of the 6th Dalai Lama.",
    "culture": "Deeply Tibetan Buddhist. The Monpa tribe constitutes the majority population, celebrating Losar (Tibetan New Year) and Torgya festival.",
    "language": "Monpa, Tibetan, Hindi, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 27.5861, "lng": 91.8594 },
    "latitude": 27.5861,
    "longitude": 91.8594,
    "imageUrl": "https://images.unsplash.com/photo-1589136777351-fdc9c94aa5b9?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1589136777351-fdc9c94aa5b9?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Alpine",
    "weather": "Cool pleasant summers, misty monsoons, and freezing snowy winters",
    "avgTemperature": "12°C",
    "bestTime": "March to June, September to November",
    "nearbyAirport": "Tezpur Airport (TEZ) in Assam - 320 km (12-hour hill drive)",
    "metroAvailable": false,
    "publicTransport": "Shared Tata Sumos, private utility vehicles",
    "budget": "Moderate",
    "estimatedBudgetMin": 2500,
    "estimatedBudgetMax": 8000,
    "hotels": ["Hotel Tawang Vista (Moderate)", "Hotel Gakyi Khang Zhang (Moderate)", "Tawang Inn (Budget)"],
    "luxuryHotels": ["Hotel Gakyi Khang Zhang"],
    "budgetHotels": ["Tawang Inn", "Mon-Paradise"],
    "restaurants": ["The Dragon Restaurant", "Mon-Exotic"],
    "streetFood": ["Momos", "Thukpa", "Butter Tea"],
    "localFoods": ["Zan (flatbread with soup)", "Chhurpi (yak cheese soup)", "Gyapa Khazi"],
    "shoppingAreas": ["Old Market Tawang", "Monpa Handicraft Center"],
    "nightlife": ["Early bedtime due to cold"],
    "attractions": ["Tawang Monastery", "Sela Pass (13,700 ft)", "Madhuri Lake (Sungester Lake)", "Nuranang Falls"],
    "hiddenGems": ["Chakusam Bridge", "Tawang War Memorial"],
    "adventureActivities": ["High altitude trekking", "Crossing Sela Pass in snow"],
    "familyActivities": ["Light show at War Memorial", "Boating at Madhuri Lake"],
    "coupleActivities": ["Watching sunrise over Sela Pass", "Walking near the lake"],
    "soloTravelTips": "An Inner Line Permit (ILP) is mandatory for all Indian tourists visiting Arunachal Pradesh. Make sure to procure it online in advance.",
    "safetyScore": 9,
    "averageRating": 4.8,
    "totalReviews": 6,
    "nearbyPlaces": ["Bomdila", "Dirang", "Tezpur"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Cross the frozen Sela Pass at 13,700 feet. Visit the scenic Sela Lake. Drive past Nuranang Falls.",
        "afternoonPlan": "Lunch at The Dragon. Visit Tawang Monastery, the second-largest monastery in the world.",
        "eveningPlan": "Attend the sound and light show at the Tawang War Memorial to honor the soldiers of the 1962 war.",
        "recommendedAttractions": ["Sela Pass", "Tawang Monastery"],
        "restaurants": ["The Dragon Restaurant"],
        "localFood": ["Butter Tea", "Thukpa"],
        "transportationTips": "4WD vehicles like Bolero/Scorpio are essential for mountain road conditions.",
        "estimatedDailyBudget": 3000
      }
    ]
  },
  {
    "name": "Agartala",
    "country": "India",
    "state": "Tripura",
    "city": "Agartala",
    "category": "Heritage",
    "description": "The capital of Tripura, known for its elegant royal palaces, temples, and close proximity to Bangladesh.",
    "history": "Seat of the ancient Manikya Dynasty, which ruled Tripura for centuries. Maharaja Radha Kishore Manikya built the iconic Ujjayanta Palace here in 1901.",
    "culture": "A blend of Bengali and indigenous Tripuri tribal cultures. Celebrates Durga Puja and Kharchi Puja with grand rituals.",
    "language": "Bengali, Kokborok, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 23.8315, "lng": 91.2868 },
    "latitude": 23.8315,
    "longitude": 91.2868,
    "imageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Humid subtropical",
    "weather": "Hot, humid summers, heavy monsoons, and mild, pleasant winters",
    "avgTemperature": "26°C",
    "bestTime": "October to March",
    "nearbyAirport": "Maharaja Bir Bikram Airport (IXA)",
    "metroAvailable": false,
    "publicTransport": "Auto-rickshaws, cycle-rickshaws, local buses",
    "budget": "Budget",
    "estimatedBudgetMin": 1200,
    "estimatedBudgetMax": 4500,
    "hotels": ["Ginger Agartala (Moderate)", "Hotel Polo Towers Agartala (Luxury)", "Hotel Sonar Tori (Moderate)"],
    "luxuryHotels": ["Hotel Polo Towers Agartala"],
    "budgetHotels": ["Ginger Agartala", "Hotel Welcome"],
    "restaurants": ["Sonar Tori restaurant", "The Kurry Club"],
    "streetFood": ["Mui Borok", "Bengali sweets"],
    "localFoods": ["Mui Borok (Tripuri style fish)", "Bengali fish curry", "Panch Phoron curry"],
    "shoppingAreas": ["Battala Market", "Jagannath Bari Road handicraft shops"],
    "nightlife": ["Quiet evenings, palace gardens"],
    "attractions": ["Ujjayanta Palace", "Neermahal (water palace) nearby", "Tripurasundari Temple", "Sepahijala Wildlife Sanctuary"],
    "hiddenGems": ["Unakoti rock carvings (130 km away)", "Heritage Park"],
    "adventureActivities": ["Boating at Neermahal", "Forest walks in Sepahijala"],
    "familyActivities": ["Visiting the Ujjayanta Palace gardens", "Seeing spectacled monkeys in Sepahijala"],
    "coupleActivities": ["Boat ride to Neermahal water palace at sunset"],
    "soloTravelTips": "Visit the Akhaura Integrated Check Post in the evening to see the beating retreat flag ceremony between Indian and Bangladeshi border forces.",
    "safetyScore": 9,
    "averageRating": 4.2,
    "totalReviews": 3,
    "nearbyPlaces": ["Neermahal", "Udaipur", "Unakoti"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Explore the white Ujjayanta Palace in the city center, which now houses the state museum.",
        "afternoonPlan": "Lunch at Sonar Tori. Travel 50 km to Melaghar and take a boat to Neermahal, the water palace in Rudrasagar Lake.",
        "eveningPlan": "Return to Agartala and attend the Indo-Bangladesh border flag ceremony at Akhaura checkpoint.",
        "recommendedAttractions": ["Ujjayanta Palace", "Neermahal"],
        "restaurants": ["Sonar Tori"],
        "localFood": ["Mui Borok"],
        "transportationTips": "Auto rickshaws are cheap and run on shared routes throughout Agartala.",
        "estimatedDailyBudget": 1800
      }
    ]
  },
  {
    "name": "Chandigarh",
    "country": "India",
    "state": "Chandigarh",
    "city": "Chandigarh",
    "category": "Metro",
    "description": "India's first planned city, designed by French architect Le Corbusier, famous for its urban architecture and public parks.",
    "history": "Conceived post-partition in 1947 to serve as the capital of East Punjab. Le Corbusier designed the master plan in the 1950s. Today, it serves as the capital of both Punjab and Haryana.",
    "culture": "A clean, modern city with a strong Punjabi lifestyle. Known for high civic sense, organized sectors, and vibrant cafe culture.",
    "language": "Punjabi, Hindi, English",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 30.7333, "lng": 76.7794 },
    "latitude": 30.7333,
    "longitude": 76.7794,
    "imageUrl": "https://images.unsplash.com/photo-1595928642581-f50f4f3453a5?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1595928642581-f50f4f3453a5?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Subtropical monsoon",
    "weather": "Hot summers, monsoon rains, and cold winters",
    "avgTemperature": "24°C",
    "bestTime": "October to March",
    "nearbyAirport": "Shaheed Bhagat Singh International Airport (IXC)",
    "metroAvailable": false,
    "publicTransport": "CTU city buses, auto-rickshaws, Ola, Uber",
    "budget": "Moderate",
    "estimatedBudgetMin": 2000,
    "estimatedBudgetMax": 8000,
    "hotels": ["Taj Chandigarh (Luxury)", "JW Marriott Chandigarh (Luxury)", "Hotel Mountview (Moderate)"],
    "luxuryHotels": ["Taj Chandigarh", "JW Marriott"],
    "budgetHotels": ["Ginger Chandigarh", "Hotel Landmark"],
    "restaurants": ["Garg Chaudhry", "Pal Dhaba (authentic Punjabi)", "Whistling Duck"],
    "streetFood": ["Gol Gappe", "Paneer Tikka", "Chhole Bhature"],
    "localFoods": ["Butter Chicken", "Sarson ka Saag & Makki di Roti", "Dal Makhani"],
    "shoppingAreas": ["Sector 17 Plaza", "Elante Mall"],
    "nightlife": ["Sector 26 microbreweries", "Sector 35 lounge bars"],
    "attractions": ["Rock Garden", "Sukhna Lake", "Rose Garden", "Capitol Complex (UNESCO)"],
    "hiddenGems": ["Pinjore Gardens nearby", "Le Corbusier Centre"],
    "adventureActivities": ["Boating at Sukhna Lake", "Cycling in Leisure Valley"],
    "familyActivities": ["Picnic at Rose Garden", "Exploring the unique recycled sculptures of Rock Garden"],
    "coupleActivities": ["Sunset boat ride at Sukhna Lake", "Dinner in Sector 26"],
    "soloTravelTips": "The city is divided into Sectors. Rent a bicycle through the city app (SmartBike) to commute cleanly.",
    "safetyScore": 10,
    "averageRating": 4.5,
    "totalReviews": 4,
    "nearbyPlaces": ["Shimla", "Amritsar", "Delhi"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Explore Nek Chand's famous Rock Garden, constructed entirely from recycled industrial and home waste.",
        "afternoonPlan": "Lunch at Pal Dhaba for authentic Punjabi butter chicken. Visit the Rose Garden in Sector 16.",
        "eveningPlan": "Relax and take a boat ride at Sukhna Lake, then head to Elante Mall for dinner and shopping.",
        "recommendedAttractions": ["Rock Garden", "Sukhna Lake"],
        "restaurants": ["Pal Dhaba"],
        "localFood": ["Butter Chicken"],
        "transportationTips": "CTU local AC buses connect all major sectors cleanly.",
        "estimatedDailyBudget": 2000
      }
    ]
  },
  {
    "name": "Diu",
    "country": "India",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "city": "Diu",
    "category": "Beach",
    "description": "A quiet coastal island fortress town off the coast of Gujarat, renowned for its Portuguese heritage, historic fort, and empty sandy beaches.",
    "history": "A Portuguese colony from 1535 until it was liberated by the Indian Armed Forces in 1961 during Operation Vijay. The Diu Fort was built by the Portuguese in 1535.",
    "culture": "A unique blend of Gujarati and Portuguese cultures. The local architecture, churches, and seafood reflect this dual history.",
    "language": "Gujarati, Portuguese, English, Hindi",
    "currency": "Indian Rupee (INR)",
    "coordinates": { "lat": 20.7144, "lng": 70.9822 },
    "latitude": 20.7144,
    "longitude": 70.9822,
    "imageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    "gallery": [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80"
    ],
    "climate": "Tropical hot",
    "weather": "Warm coastal weather throughout the year, sea breezes, and light monsoon rains",
    "avgTemperature": "26°C",
    "bestTime": "October to March",
    "nearbyAirport": "Diu Airport (DIU)",
    "metroAvailable": false,
    "publicTransport": "Bicycle rentals, scooter rentals, local auto-rickshaws",
    "budget": "Moderate",
    "estimatedBudgetMin": 1500,
    "estimatedBudgetMax": 5500,
    "hotels": ["Radhika Beach Resort (Moderate)", "Rann Riders (Moderate)", "Hotel Heranca Goesa (Budget)"],
    "luxuryHotels": ["Radhika Beach Resort", "Azzaro Resorts Spa"],
    "budgetHotels": ["Hotel Heranca Goesa", "Diu Tourist Hostel"],
    "restaurants": ["O'Coqueiro (Portuguese-style garden cafe)", "Apana Foodland"],
    "streetFood": ["Lobster", "Prawns at beach shacks"],
    "localFoods": ["Portuguese fish curry", "Seafood platters", "Gujarati Kadhi"],
    "shoppingAreas": ["Diu Local Market"],
    "nightlife": ["Beachside bars (alcohol is permitted here, unlike dry Gujarat next door)"],
    "attractions": ["Diu Fort", "Naida Caves", "Gangeshwar Mahadev Temple", "Nagoa Beach"],
    "hiddenGems": ["St. Paul's Church", "Sunset Point Beach"],
    "adventureActivities": ["Parasailing at Nagoa Beach", "Jet skiing"],
    "familyActivities": ["Exploring the massive maze of Naida Caves", "Touring the cannons at Diu Fort"],
    "coupleActivities": ["Sunset walk along Nagoa beach, dining in garden cafes"],
    "soloTravelTips": "Rent a scooter or bicycle. The island is small, flat, and extremely scenic, making it perfect for two wheelers.",
    "safetyScore": 10,
    "averageRating": 4.4,
    "totalReviews": 3,
    "nearbyPlaces": ["Somnath", "Gir National Park", "Veraval"],
    "sampleItinerary": [
      {
        "dayNumber": 1,
        "morningPlan": "Explore the massive stone walls of the 16th century Diu Fort. Photograph the labyrinthine Naida Caves.",
        "afternoonPlan": "Lunch at O'Coqueiro. Visit the Gangeshwar Mahadev Temple, where Shiva Lingas are washed by waves.",
        "eveningPlan": "Relax and try water sports at Nagoa Beach, then watch the sunset at Sunset Point.",
        "recommendedAttractions": ["Diu Fort", "Naida Caves"],
        "restaurants": ["O'Coqueiro"],
        "localFood": ["Lobster"],
        "transportationTips": "Rent a scooter for 400 INR per day to move around freely.",
        "estimatedDailyBudget": 2000
      }
    ]
  }
];

module.exports = { supplementaryDestinations };
